server:
  port: 8080  # API Gateway should run on its own port

spring:
  application:
    name: api-gateway  # API Gateway service name

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
